[[file_type]]
extension = "jpg"
headers = [ [ 0xff, 0xd8, 0xff, 0xe0 ], [ 0xff, 0xd8, 0xff, 0xe1 ] ]
footers = [ [ 0xff, 0xd9 ] ]
max_len = 10485760
pairing = "next"
type_id = "jpeg"

[[file_type]]
extension = "png"
headers = [ [ 0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a ] ]
footer = [ [ 0x49, 0x45, 0x4e, 0x44, 0xae, 0x42, 0x60, 0x82 ] ]
max_len = 10485760
pairing = "next"
type_id = "png"